# Generated by Django 3.2.8 on 2021-11-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_joined', models.DateField(max_length=100)),
                ('date_of_left', models.DateField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('band_id', models.IntegerField()),
                ('release_date', models.DateField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.albums')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.artists')),
            ],
        ),
        migrations.CreateModel(
            name='CopyRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.IntegerField()),
                ('release_date', models.DateField()),
                ('is_valid', models.BooleanField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.albums')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.songs')),
            ],
        ),
        migrations.AddField(
            model_name='artists',
            name='band_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.bands'),
        ),
        migrations.AddField(
            model_name='albums',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.artists'),
        ),
        migrations.AddField(
            model_name='albums',
            name='band_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.bands'),
        ),
    ]
